name: Directory push/pop
author: Philip Colmer (Linaro Ltd)
branding:
  icon: "archive"
  color: "green"
description: |
  Moves a named directory out of a cache and back again.
inputs:
  cacheDirectory:
    description: "Path to the directory used to store directories"
    required: true
  namedDirectory:
    description: "Name of the directory to move"
    required: true
  destinationDirectory:
    description: "Where to move the named directory to"
    required: false
runs:
  using: "node12"
  main: 'directory-out.js'
  post: 'directory-in.js'
